### ISSUE TITLE
Use ordered links for bonds, insted of unordered links.

### ISSUE THREAD

**Issue by linas** [opencog/cheminformatics#1]
The use of unordered links has a strongly negative impact on search performance. When searching for any given bond, two permutations must be explored: the atoms one way, and the atoms swapped.  For N bonds in a molecule, this requires 2^N different comparisons to be performed! Ouch! 

To be precise: change the single, double bonds to be ordered links (e.g. `ListLink`)

Suggest the following ordering rules:
* For any bond, always write H last.  Thus `CH`, `NH` and `OH`and never  `HC`, `HN`, `HO`
* For everything else, the lighter atom comes first, thus `NO` and `NaCl` instead of`ON`, `ClNa`.

You can make up any rules you want as long as they are consistently applied. The query engine does not care. The above are what seemed to make sense to me.

@robert-haas Hope you see this bug report.

**Comment by robert-haas** [comment]
Thanks, I've changed the link type of bonds to increase the performance of pattern matching.

There are some rules in chemistry for what elements are listed first in bonds, but I'm not sure if there is a well-defined convention that could be reused here. Your suggestion is a good start, but here's a counter example: KCl is preferred over ClK, so "lighter atom first" might need further exceptions. I'll see if I find a convention or try to come up with a suitable one and will add it to the main README.

**Comment by linas** [comment]
OK. Closing this issue ...
