### ISSUE TITLE
Latest version of AtomSpace is needed

### ISSUE THREAD

**Issue by linas** [opencog/cheminformatics#2]
@robert-haas This is an FYI message -- As you are vaguely aware, the cheminformatics search patterns (as demoed in `reaction.scm`) are flexing some brand-new code in the atomspace query engine. Since it was brand-new .. it had some bugs... which are now fixed. So please pull & build the current version of the AtomSpace.

There were two bugs; both involved a failure to explore all possible groundings (a "grounding" is an assignment of atoms to variables).

Close this issue whenever you're ready.

**Comment by robert-haas** [comment]
Thank you @linas. The esterification example works now in Scheme and Python (after porting your fix of reaction.scm). `ORDERED_LINK` for bond types together with the updated atomspace installation produces the expected results.
